/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;
import Otros.TextPrompt;
import Entidades.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mco_a
 */
public class GestorCursos extends javax.swing.JFrame {

    private ListaProfesores listaProfesores;
    private ListaEstudiantes listaEstudiantes;
    
    private List<Curso> cursos 
            = new ArrayList<>();
    
    private DefaultListModel listaCursos 
            = new DefaultListModel();
    /**
     * Creates new form GestorCursos
     */
    public GestorCursos() {
        initComponents();
        
        TextPrompt txtPrompt = new TextPrompt("Buscar", txtBusqueda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        txtBusqueda = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        btnEstudiantes = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setForeground(new java.awt.Color(153, 153, 153));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-CelesteClaro.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 327, -1, -1));

        jScrollPane1.setBorder(null);

        lstCursos.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstCursos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 450, 180));

        txtBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setBorder(null);
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 300, 30));

        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-RojoClaro2.png"))); // NOI18N
        btnEliminar.setText("-");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 327, 45, 32));

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-Verde.png"))); // NOI18N
        btnAgregar.setText("+");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 327, 45, 32));

        btnEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-Azulino.png"))); // NOI18N
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseExited(evt);
            }
        });
        jPanel1.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 327, 90, 32));

        btnProfesores.setForeground(new java.awt.Color(0, 0, 0));
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-Azulino.png"))); // NOI18N
        btnProfesores.setText("Profesores");
        btnProfesores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseExited(evt);
            }
        });
        jPanel1.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 327, 90, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo-Lista.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 104, 473, 190));

        btnBuscar.setForeground(new java.awt.Color(153, 153, 153));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Btn-VerdeClaro.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 59, 90, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo-TextField.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 59, 323, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestor de Cursos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 16, 234, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 528, 392));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        EditarCurso pantalla = new EditarCurso(this);
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarMouseClicked

    public void agregarCurso(Curso curso){
        
        cursos.add(curso);
        actualizarLista();
    }
    
    public void editarCurso(Curso curso, int index){
        
        Curso cursoAnterior = cursos.get(index);
        
        cursoAnterior.setCodigo(
                curso.getCodigo());
        cursoAnterior.setCreditos(
                curso.getCreditos());
        cursoAnterior.setNombre(
                curso.getNombre());
 
        actualizarLista();
    }
    
    public void actualizarLista(){
        listaCursos.removeAllElements();
        for(Curso curso: this.cursos){
            listaCursos.addElement(
                    curso.getTexto());
        }
        lstCursos.setModel(listaCursos);
    }
    
    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-VerdeIntenso.png"))
        );
        btnAgregar.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-Verde.png"))
        );
        btnAgregar.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int index = lstCursos.getSelectedIndex();
        if(index == -1){
            JOptionPane.showMessageDialog(
                    this, 
                    "Seleccione un curso");
        } else {
            cursos.remove(index);
            listaCursos.remove(index);
            // Establecer el modelo actualizado en el JList
            lstCursos.setModel(listaCursos); 
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-Rojo.png"))
        );
        btnEliminar.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-RojoClaro2.png"))
        );
        btnEliminar.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        int index = lstCursos.getSelectedIndex();
        if(index == -1){
            JOptionPane.showMessageDialog(
                    this, 
                    "Seleccione un curso");
            return;
        }
        
        Curso cursoSelec = cursos.get(index);
        
        EditarCurso pantalla = new EditarCurso(
                this, 
                cursoSelec,
                index);
        
        pantalla.setLocationRelativeTo(this);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        btnEditar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-Celeste.png"))
        );
        btnEditar.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
         btnEditar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-CelesteClaro.png"))
        );
        btnEditar.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        
        txtBusqueda.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            // No realiza búsqueda automática aquí
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
            // Cuando se borra el texto, se restaura la lista completa
                if (txtBusqueda.getText().trim().isEmpty()) {
                    lstCursos.setModel(listaCursos);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            // No realiza búsqueda automática aquí
            }
        });
        
        // Obtiene el texto de búsqueda en minúsculas
        String textoBusqueda = txtBusqueda.getText().trim().toLowerCase();

        if (textoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, ingresa un término de búsqueda "
                            + "antes de hacer clic en Buscar.", 
                    "Campo de búsqueda vacío", 
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            // Crea un modelo para los resultados
            DefaultListModel resultadosModel = new DefaultListModel(); 

            for (Curso curso : cursos) {
                // Obtiene el codigo y nombre del estudiante en minúsculas
                String codigoCurso = 
                        curso.getCodigo().toLowerCase(); 
                
                String nombreCurso =
                        curso.getNombre().toLowerCase();
            
                // Agrega los cursos al modelo de resultados
                if (codigoCurso.contains(textoBusqueda) || 
                        nombreCurso.contains(textoBusqueda))
                {
                    resultadosModel.addElement(
                            curso.getTexto()); 
                }
            }
        
            if (resultadosModel.isEmpty()) {
                // Muestra un mensaje si no se encontraron resultados
                JOptionPane.showMessageDialog(this, 
                        "No se encontraron resultados"
                                + " para la búsqueda.",
                        "Sin resultados", 
                        JOptionPane.INFORMATION_MESSAGE
                );
            
                // Restablece el modelo original
                lstCursos.setModel(listaCursos);
            } else {
                // Configura el modelo de resultados
                lstCursos.setModel(resultadosModel);
            }
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-VerdeClaro2.png"))
        );
        btnBuscar.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-VerdeClaro.png"))
        );
        btnBuscar.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseClicked
        if(listaProfesores == null){
            listaProfesores = new ListaProfesores(this);
        }
        listaProfesores.setLocationRelativeTo(this);
        listaProfesores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfesoresMouseClicked

    private void btnProfesoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseEntered
        btnProfesores.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-AzulIntenso.png"))
        );
        btnProfesores.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnProfesoresMouseEntered

    private void btnProfesoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseExited
        btnProfesores.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-Azulino.png"))
        );
        btnProfesores.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnProfesoresMouseExited

    private void btnEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseClicked
        if(listaEstudiantes == null){
            listaEstudiantes = new ListaEstudiantes(this);
        }
        listaEstudiantes.setLocationRelativeTo(this);
        listaEstudiantes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstudiantesMouseClicked

    private void btnEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseEntered
        btnEstudiantes.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-AzulIntenso.png"))
        );
        btnEstudiantes.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnEstudiantesMouseEntered

    private void btnEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseExited
        btnEstudiantes.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/Imgs/Btn-Azulino.png"))
        );
        btnEstudiantes.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnEstudiantesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnEstudiantes;
    private javax.swing.JLabel btnProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
